name: medkit_app
description: "Medical appointment booking app for patients"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1

  # HTTP & API
  dio: ^5.9.2

  # Local Storage
  shared_preferences: ^2.5.5

  # Date & Time
  intl: ^0.20.2

  # UI Components
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1

  # File handling
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  image_cropper: ^12.2.1

  # Icons
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
